workspace:
  base: /var/www/owncloud
  path: apps/notifications


pipeline:
  install-core:
    image: owncloudci/core
    version: ${OC_VERSION}
    pull: true
    db_type: ${DB_TYPE}
    db_name: ${DB_NAME}
    db_host: ${DB_TYPE}
    db_username: autotest
    db_password: owncloud
    exclude: apps/notifications
    when:
      matrix:
        NEED_CORE: true

  install-testrunner:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - git clone -b master --depth=1 https://github.com/owncloud/core.git /var/www/owncloud/testrunner
      - cp -r /var/www/owncloud/apps/notifications /var/www/owncloud/testrunner/apps/
      - cd /var/www/owncloud/testrunner
      - make install-composer-deps
      - make vendor-bin-deps
    when:
      matrix:
        USE_RELEASE_TARBALL: true

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ log:manage --level 0
    when:
      matrix:
        NEED_INSTALL_APP: true

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log
    when:
      matrix:
        NEED_SERVER: true

  owncloud-coding-standard:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: owncloud-coding-standard

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /var/www/owncloud -R
      - if [ "${USE_RELEASE_TARBALL}" = "true" ];
        then
        chmod 777 /var/www/owncloud/testrunner/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/testrunner/tests/acceptance/run.sh;
        else
        chmod 777 /var/www/owncloud/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/tests/acceptance/run.sh;
        fi
    when:
      matrix:
        NEED_SERVER: true

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_SERVER_URL=http://owncloud
      - PLATFORM=Linux
      - BEHAT_SUITE=${BEHAT_SUITE}
      - APPS_TO_ENABLE=notifications
    commands:
      - if [ "${USE_RELEASE_TARBALL}" = "true" ]; then cd /var/www/owncloud/testrunner/apps/notifications; fi
      - make test-acceptance-webui
    when:
      matrix:
        TEST_SUITE: web-acceptance

  api-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://owncloud
      - MAILHOG_HOST=email
      - BEHAT_SUITE=${BEHAT_SUITE}
      - APPS_TO_ENABLE=notifications
    commands:
      - if [ "${USE_RELEASE_TARBALL}" = "true" ]; then cd /var/www/owncloud/testrunner/apps/notifications; fi
      - make test-acceptance-api
    when:
      matrix:
        TEST_SUITE: api-acceptance

  cli-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://owncloud
      - PLATFORM=Linux
      - BEHAT_SUITE=${BEHAT_SUITE}
      - APPS_TO_ENABLE=notifications
    commands:
      - if [ "${USE_RELEASE_TARBALL}" = "true" ]; then cd /var/www/owncloud/testrunner/apps/notifications; fi
      - make test-acceptance-cli
    when:
      matrix:
        TEST_SUITE: cli-acceptance

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COVERAGE=${COVERAGE}
    commands:
      - if [ -z "${COVERAGE}" ]; then make test-php-unit; fi
      - if [ "${COVERAGE}" = "true" ]; then make test-php-unit-dbg; fi
    when:
      matrix:
        TEST_SUITE: phpunit

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    flags:
      - ${TEST_SUITE}
    files:
      - tests/output/clover.xml
    when:
      event: [push, pull_request]
      matrix:
        COVERAGE: true

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [slack_webhook]
    channel: builds
    when:
      status: [failure, changed]
      event: [push, tag]

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  pgsql:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=autotest
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: pgsql

  oci:
    image: deepdiver/docker-oracle-xe-11g
    environment:
       - ORACLE_USER=system
       - ORACLE_PASSWORD=oracle
       - ORACLE_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: oci

  owncloud:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND" ]
    when:
      matrix:
        NEED_SERVER: true

  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    pull: true
    when:
      matrix:
        TEST_SUITE: web-acceptance

  email:
    image: mailhog/mailhog
    pull: true
    when:
      matrix:
        TEST_SUITE: api-acceptance

matrix:
  include:
      # owncloud-coding-standard
    - PHP_VERSION: 7.2
      TEST_SUITE: owncloud-coding-standard

    - PHP_VERSION: 7.0
      TEST_SUITE: owncloud-coding-standard

    # Unit Tests
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.3
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true

    # Acceptance Tests

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUINotifications
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUINotifications
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUINotifications
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiNotifications
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiNotifications
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiNotifications
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: cli-acceptance
      BEHAT_SUITE: cliNotifications
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: cli-acceptance
      BEHAT_SUITE: cliNotifications
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: cli-acceptance
      BEHAT_SUITE: cliNotifications
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUINotifications
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiNotifications
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: cli-acceptance
      BEHAT_SUITE: cliNotifications
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true

    # Tests against latest stable release of core
    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: cli-acceptance
      BEHAT_SUITE: cliNotifications
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true
      USE_RELEASE_TARBALL: true

    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUINotifications
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true
      USE_RELEASE_TARBALL: true

    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiNotifications
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      NEED_SERVER: true
      USE_RELEASE_TARBALL: true
